### ISSUE TITLE
❌ an integer is required (got type str) - Problem while using the software

### ISSUE THREAD

**Issue by mmuncan** [rm1984/IMAPLoginTester#1]
I think there is a problem getting it to run on windows 10. please have a look ;)

C:\Users\XXX\Desktop\IMAPLoginTester-main>python imaplogintester.py -i target.txt -o target_0ut.txt -s -t 3 -T 25 -v
E-Mails file:  target.txt
Output file:   target_0ut.txt
Sleep time:    3 seconds
Login timeout: 25 seconds
SOCKS5 proxy:  None

❌ an integer is required (got type str)
❌ an integer is required (got type str)
<frame at 0x00000248F497A610, file 'C:\\Users\\mmunc\\Desktop\\IMAPLoginTester-main\\imaplogintester.py', line 217, code main>
You pressed Ctrl+C!
Goodbye!

a longer logfile which was created before:
❌ [Errno 11004] getaddrinfo failed
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ [Errno 11004] getaddrinfo failed
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ [Errno 11004] getaddrinfo failed
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mgraduateinstitute.ch←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlucien.nyc←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33moptonline.net←[0m
⚠ Missing config section for domain: ←[33moptimum.net←[0m
⚠ Missing config section for domain: ←[33mcox.net←[0m
⚠ Missing config section for domain: ←[33mprodigy.net.mx←[0m
⚠ Missing config section for domain: ←[33mcharter.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33moptonline.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33msbcglobal.net←[0m
⚠ Missing config section for domain: ←[33mcox.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33moptonline.net←[0m
⚠ Missing config section for domain: ←[33mlineone.net←[0m
⚠ Missing config section for domain: ←[33mearthlink.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33moptonline.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33mcharter.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33membarqmail.com←[0m
⚠ Missing config section for domain: ←[33mmyfairpoint.net←[0m
⚠ Missing config section for domain: ←[33mcomcast.net←[0m
⚠ Missing config section for domain: ←[33mntlworld.com←[0m
⚠ Missing config section for domain: ←[33mzoominternet.net←[0m
⚠ Missing config section for domain: ←[33mcox.net←[0m
⚠ Missing config section for domain: ←[33mprodigy.net.mx←[0m
⚠ Missing config section for domain: ←[33mzoominternet.net←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mkarolinahaglund.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mberghem-sala.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mtelia.com←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mhotmail.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ [Errno 11004] getaddrinfo failed
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ [Errno 11004] getaddrinfo failed
⚠ Missing config section for domain: ←[33mswipnet.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mdevelopme.se←[0m
⚠ Missing config section for domain: ←[33mhelenabielke.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mspray.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mhotmail.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mtelia.com←[0m
⚠ Missing config section for domain: ←[33mguldsmedpetersson.se←[0m
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mpostnord.com←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
⚠ Missing config section for domain: ←[33mcomhem.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ [Errno 11004] getaddrinfo failed
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
⚠ Missing config section for domain: ←[33mspray.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mhotmail.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.no←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mcambiache.com←[0m
⚠ Missing config section for domain: ←[33mtele2.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mdanskebank.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mkennethhelle.se←[0m
⚠ Missing config section for domain: ←[33mtelia.com←[0m
⚠ Missing config section for domain: ←[33mhotmail.se←[0m
⚠ Missing config section for domain: ←[33mspray.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mtelia.com←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mgruvstad.se←[0m
❌ [Errno 11004] getaddrinfo failed
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mhome.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mbojdslojd.com←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mcomhem.se←[0m
⚠ Missing config section for domain: ←[33mtelia.com←[0m
⚠ Missing config section for domain: ←[33mhotmail.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33myahoo.se←[0m
❌ [Errno 11004] getaddrinfo failed
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mkommunal.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mspray.se←[0m
⚠ Missing config section for domain: ←[33msophies.se←[0m
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
❌ an integer is required (got type str)
⚠ Missing config section for domain: ←[33mlive.se←[0m
⚠ Missing config section for domain: ←[33mlive.se←[0m
⚠ Missing config section for domain: ←[33mhotmail.co.uk←[0m
<frame at 0x000002A1F0C5ECF0, file 'C:\\Users\\mmunc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\validators\\domain.py', line 60, code domain>
You pressed Ctrl+C!
Goodbye!

**Comment by rm1984** [comment]
Hi,
I missed an integer cast.
It should be ok now.
Thank you!
